### ISSUE TITLE
"Electron failed to install correctly".

### ISSUE THREAD

**Issue by Faares** [faressoft/terminalizer#107]
I install the program on Ubuntu 20.04LTS, but when I try to run it, the following error appears:
``
/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
``
I tried to remove it, and then install it again, but still, the problem is there.

any help?

**[UPDATE]:** the problem was that the `Electron` package didn't install.  so I install it manually using the following command:
``node /usr/local/lib/node_modules/terminalizer/node_modules/electron/install.js``
but.. another error appears:

``
innerError { Error: Cannot find module '../build/Debug/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/unixTerminal.js:35
        throw outerError;
        ^
Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
``

**Comment by Faares** [comment]
I solve the previous error. using the following commands:
```
cd $(npm -g prefix)/lib/node_modules
sudo npm rebuild
```
