### ISSUE TITLE
Electron failed to install correctly

### ISSUE THREAD

**Issue by psyhomb** [faressoft/terminalizer#117]
```
root@test:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
root@test:~# 
```

```
root@test:~# terminalizer --help
/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:18:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Proxy.DI.require (/usr/local/lib/node_modules/terminalizer/di.js:105:29)
root@test:~#
```

**Comment by Morojs** [comment]
Try
```
npm install electron --verbose

```
It should output a progress bar for the download

**Comment by maxboone** [comment]
```bash
user@foo ~ % npm --version
6.14.8
user@foo ~ % node --version
v12.15.0
user@foo ~ % electron --version
v10.1.5
```

Same error, on macOS. Electron runs fine: [screenshot of the electron command](https://imgur.com/a/xfqvoqv)

Installing the node module as root or as current user doesn't do difference either, even though I have to say that it's worrisome that proposed fixes are installing node modules as root _(post-install scripts anyone?)_

**Comment by teauxfu** [comment]
If anyone else is struggling with this issue check
https://github.com/faressoft/terminalizer/issues/132#issuecomment-822942731
