### ISSUE TITLE
Electron failed to install correctly

### ISSUE THREAD

**Issue by rabestro** [faressoft/terminalizer#132]
How to install it on Ubuntu 20.04? 

<pre>$ sudo npm install npm@latest -g
/usr/local/bin/npm -&gt; /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -&gt; /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.8
added 434 packages from 885 contributors in 4.53s
</pre>

<pre>sudo npm install -g terminalizer
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> har-validator@5.1.5: this library is no longer supported
/usr/local/bin/terminalizer -&gt; /usr/local/lib/node_modules/terminalizer/bin/app.js
+ terminalizer@0.7.2
updated 1 package in 16.825s
</pre>

<pre>$ terminalizer record demo
/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14
    throw new Error(&apos;Electron failed to install correctly, please delete node_modules/electron and try installing again&apos;)
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14:11)
    at Object.&lt;anonymous&gt; (/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Proxy.DI.require (/usr/local/lib/node_modules/terminalizer/di.js:105:29)
</pre>

**Comment by Nightreaver** [comment]
I had same issue, i installed under root (without sudo) and it worked much better.
Secondly you can try some other solutions, some people already had same issue.


```
sudo su -
npm install -g terminalizer --unsafe
```
> `--unsafe` was to fix an issue with node-gyp running into issues under root

**Comment by maxboone** [comment]
> I had same issue, i installed under root (without sudo) and it worked much better.
> Secondly you can try some other solutions, some people already had same issue.
> 
> ```
> sudo su -
> npm install -g terminalizer --unsafe
> ```
> 
> > `--unsafe` was to fix an issue with node-gyp running into issues under root

On MacOS

Installing the package either as root or as current user with the unsafe flag doesn't solve this issue. Besides the fact that i **never** install npm packages as root (allowing for post-install execution at superuser level) this problem seems to persist in both cases.

**Comment by Notespeak** [comment]
Similar issue on ubuntu 20.04. I am completely unable to make this sofware work, even though I tried everything mentioned in this thread. Works under deb 10 though ).
Here is the error output:
root@localhost:/# terminalizer
/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Proxy.DI.require (/usr/local/lib/node_modules/terminalizer/di.js:105:29)

**Comment by bscott** [comment]
Having same issues

**Comment by teauxfu** [comment]
To anyone having this issue, try to install an older version of node
note the installation instructions @ https://terminalizer.com/install

> The installation should be very smooth with Node.js v4-v12.

I used [nvm ](https://github.com/nvm-sh/nvm) to install the latest node version 12
then, I was able to install terminalizer and run it without issue

this was on WSL2 with ubuntu 20.04

hope this helps

**Comment by khuyentran1401** [comment]
> To anyone having this issue, try to install an older version of node
> note the installation instructions @ https://terminalizer.com/install
> 
> > The installation should be very smooth with Node.js v4-v12.
> 
> I used [nvm ](https://github.com/nvm-sh/nvm) to install the latest node version 12
> 
> `nvm install 12`
> `nvm use 12`
> then, I was able to install terminalizer and run it without issue
> `npm install -g terminalizer`
> `terminalizer --version `
> 
> this was on WSL2 with ubuntu 20.04
> 
> hope this helps

This works for me! Thank you.
