### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by erotavlas** [faressoft/terminalizer#139]
I just installed terminalizer on Windows 10 and when I tried to record my terminal it fails with the following errors

```
PS E:\SOFTWARE_DEVELOPMENT> terminalizer record demo
innerError Error: Cannot find module '../build/Debug/conpty.node'
Require stack:
- C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\node_modules\@faressoft\node-pty-prebuilt\lib\windowsPtyAgent.js
- C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\node_modules\@faressoft\node-pty-prebuilt\lib\windowsTerminal.js
- C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\node_modules\@faressoft\node-pty-prebuilt\lib\index.js
- C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\app.js
- C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\bin\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at new WindowsPtyAgent (C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\node_modules\@faressoft\node-pty-prebuilt\lib\windowsPtyAgent.js:39:40)
    at new WindowsTerminal (C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\node_modules\@faressoft\node-pty-prebuilt\lib\windowsTerminal.js:49:24)
rebuilt\lib\index.js:28:12)
    at command (C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\commands\record.js:219:27)
    at Object.module.exports.handler (C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\commands\record.js:276:3)
    at Object.runCommand (C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\node_modules\yargs\lib\command.js:238:44) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\terminalizer\\node_modules\\@faressoft\\node-pty-prebuilt\\lib\\windowsPtyAgent.js',
    'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\terminalizer\\node_modules\\@faressoft\\node-pty-prebuilt\\lib\\windowsTerminal.js',
    'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\terminalizer\\node_modules\\@faressoft\\node-pty-prebuilt\\lib\\index.js',
    'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\terminalizer\\app.js',
    'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\terminalizer\\bin\\app.js'
  ]
}
Error:
  Error: The module '\\?\C:\Users\username\AppData\Roaming\npm\node_modules\terminalizer\node_modules\@faressoft\node-pty-prebuilt\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Hint:
  Use the --help option to get help about the usage
```

**Comment by jef** [comment]
> The installation should be very smooth with Node.js v4-v12. For newer versions, if the installation is failed, you may need to install the development tools to build the C++ add-ons. Check node-gyp.

**Comment by JanC** [comment]
@jef 
I have a simular error but I do have Node v12:

```
node --version
v12.19.0
```

```
terminalizer record demo
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/unixTerminal.js
- /usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/index.js
- /usr/local/lib/node_modules/terminalizer/app.js
- /usr/local/lib/node_modules/terminalizer/bin/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/index.js',
    '/usr/local/lib/node_modules/terminalizer/app.js',
    '/usr/local/lib/node_modules/terminalizer/bin/app.js'
  ]
}
/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: The module '/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1065:18)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/@faressoft/node-pty-prebuilt/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

**Comment by jef** [comment]
Looks like you need to do `npm install` or `nom rebuild`

**Comment by JanC** [comment]
ah actually installing from the sources works. 

thanks
