### ISSUE TITLE
Can't install since Python is too new

### ISSUE THREAD

**Issue by neilco** [faressoft/terminalizer#16]
When I attempt to install on macOS 10.13.6, it fails because my version of Python is too new. 

```shell
$ python -V
Python 3.7.0
```

This version of Python was previously installed using Homebrew. 

```shell
$ npm i -g terminalizer
/usr/local/bin/terminalizer -> /usr/local/lib/node_modules/terminalizer/bin/app.js

> node-pty-prebuilt@0.7.3 install /usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=10.1.0 runtime=node arch=x64 platform=darwin)
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/usr/local/bin/python" is v3.7.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:273:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:378:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:598:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt@0.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/neil/.npm/_logs/2018-08-03T08_03_27_250Z-debug.log
```

The solution was to temporarily unlink the Homebrew version of Python (`brew unlink python`) to revert back to the system-installed version (Python 2.7.10), install terminalizer, and then relink Python 3. 

Reporting this as there's no mention of Python version requirements in the README.

**Comment by faressoft** [comment]
You can find the path of python 2 and use the option `--python` with `npm install -g terminalizer`.

Or just use an older version of Node.js since v10 is not supported yet for our prebuilt dependencies.
