### ISSUE TITLE
Install fail on Windows 10

### ISSUE THREAD

**Issue by hantatsang** [faressoft/terminalizer#36]
I tried to install on 2 different Windows 10 machines but both fails.
Retried on a Mac and it worked.

I have referred to issue #16 but it doesn't resolve my case.

### Versions

```
nvm v1.1.7
node v11.1.0
npm v6.4.1
python v3.7.0
```

### Error log

```
 npm i -g terminalizer
C:\Program Files\nodejs\terminalizer -> C:\Program Files\nodejs\node_modules\terminalizer\bin\app.js

> node-pty-prebuilt@0.7.6 install C:\Program Files\nodejs\node_modules\terminalizer\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=11.1.0 runtime=node arch=x64 platform=win32)

C:\ProgramData\nvm\v11.1.0\node_modules\terminalizer\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\ProgramData\nvm\v11.1.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\ProgramData\nvm\v11.1.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\tools\miniconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\nvm\\v11.1.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\ProgramData\nvm\v11.1.0\node_modules\terminalizer\node_modules\node-pty-prebuilt
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-11-07T23_45_34_574Z-debug.log
```

**Comment by hantatsang** [comment]
Thanks!

Installing the development tools work for me:

```shell
npm install --global --production windows-build-tools

npm i -g terminalizer
```

**Comment by namdien177** [comment]
> Thanks!
> 
> Installing the development tools work for me:
> 
> ```shell
> npm install --global --production windows-build-tools
> 
> npm i -g terminalizer
> ```

I faced this issue but with node-pty.

Your solution was almost perfect. Just need to refer to this answer on Stackoverflow

[https://stackoverflow.com/a/56314445/8470827](url)
