### ISSUE TITLE
Error running terminalizer on node v11.3.0

### ISSUE THREAD

**Issue by brpaz** [faressoft/terminalizer#37]
Hello.
Got the following error when starting terminalizer:

```
Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/bruno/.nvm/versions/node/v11.3.0/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt/lib/unixTerminal.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by faressoft** [comment]
"The installation should be very smooth with Node.js v10 or lower. For newer versions, if the installation is failed, you may need to install the development tools to build the C++ add-ons. Check node-gyp."
