### ISSUE TITLE
is this thing working?

### ISSUE THREAD

**Issue by sokoow** [faressoft/terminalizer#46]
I got this after installing terminalizer with npm install -g terminalizer:

```
$ terminalizer 
/usr/local/lib/node_modules/terminalizer/node_modules/yargs/lib/command.js:22
    globalMiddleware.push(...middlewares)
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/yargs/lib/argsert.js:2:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

um, help ?

**Comment by faressoft** [comment]
@sokoow What version of Node.js do you use ?

**Comment by sokoow** [comment]
I got it working on ubuntu bionic, that was a nodejs version from ubuntu xenial that was problematic

**Comment by aminvakil** [comment]
That would be appreciated if you mentioned your nodejs version so the world could recognize and check the problem.

**Comment by sokoow** [comment]
I'm on ubuntu Xenial so it's v4.2.6
