### ISSUE TITLE
No token & errors in generating share

### ISSUE THREAD

**Issue by LodeVanB** [faressoft/terminalizer#49]
~$ terminalizer share test
Please enter some details about your recording
? Title Test
? Description Testing terminalizer
? Tags such as git,bash,game linux

/usr/local/lib/node_modules/terminalizer/commands/share.js:194
        return reject(body.errors.join('\n'));
                                  ^

TypeError: Cannot read property 'join' of undefined
    at Request._callback (/usr/local/lib/node_modules/terminalizer/commands/share.js:194:35)
    at Request.self.callback (/usr/local/lib/node_modules/terminalizer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by LodeVanB** [comment]
2nd try with demo.yml ...

TypeError: Cannot read property 'join' of undefined
    at Request._callback (/usr/local/lib/node_modules/terminalizer/commands/share.js:194:35)
    at Request.self.callback (/usr/local/lib/node_modules/terminalizer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by tyduptyler13** [comment]
I can confirm that I am getting the same errors.
