### ISSUE TITLE
Got errors during installation

### ISSUE THREAD

**Issue by JoeFirmament** [faressoft/terminalizer#80]
```shell
....
...
.....
> electron@7.1.7 postinstall /usr/lib/node_modules/terminalizer/node_modules/electron
> node install.js

/usr/lib/node_modules/terminalizer/node_modules/sumchecker/index.js:95
  async readFile (filename, binary) {
        ^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/terminalizer/node_modules/@electron/get/dist/cjs/index.js:51:18)
npm verb lifecycle electron@7.1.7~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle electron@7.1.7~postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/terminalizer/node_modules/electron/node_modules/.bin:/usr/lib/node_modules/terminalizer/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin
npm verb lifecycle electron@7.1.7~postinstall: CWD: /usr/lib/node_modules/terminalizer/node_modules/electron
npm info lifecycle electron@7.1.7~postinstall: Failed to exec postinstall script
npm verb unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
/usr/lib
└── (empty)

npm verb stack Error: electron@7.1.7 postinstall: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:920:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
npm verb pkgid electron@7.1.7
npm verb cwd /root
npm ERR! Linux 3.10.0-1062.4.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-unsafe-perm" "--verbose" "-g" "terminalizer"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@7.1.7 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@7.1.7 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

**Comment by JoeFirmament** [comment]
> ```shell
> ....
> ...
> .....
> > electron@7.1.7 postinstall /usr/lib/node_modules/terminalizer/node_modules/electron
> > node install.js
> 
> /usr/lib/node_modules/terminalizer/node_modules/sumchecker/index.js:95
>   async readFile (filename, binary) {
>         ^^^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:549:28)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/lib/node_modules/terminalizer/node_modules/@electron/get/dist/cjs/index.js:51:18)
> npm verb lifecycle electron@7.1.7~postinstall: unsafe-perm in lifecycle true
> npm verb lifecycle electron@7.1.7~postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/terminalizer/node_modules/electron/node_modules/.bin:/usr/lib/node_modules/terminalizer/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin
> npm verb lifecycle electron@7.1.7~postinstall: CWD: /usr/lib/node_modules/terminalizer/node_modules/electron
> npm info lifecycle electron@7.1.7~postinstall: Failed to exec postinstall script
> npm verb unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
> /usr/lib
> └── (empty)
> 
> npm verb stack Error: electron@7.1.7 postinstall: `node install.js`
> npm verb stack Exit status 1
> npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
> npm verb stack     at emitTwo (events.js:106:13)
> npm verb stack     at EventEmitter.emit (events.js:191:7)
> npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> npm verb stack     at emitTwo (events.js:106:13)
> npm verb stack     at ChildProcess.emit (events.js:191:7)
> npm verb stack     at maybeClose (internal/child_process.js:920:16)
> npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
> npm verb pkgid electron@7.1.7
> npm verb cwd /root
> npm ERR! Linux 3.10.0-1062.4.3.el7.x86_64
> npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-unsafe-perm" "--verbose" "-g" "terminalizer"
> npm ERR! node v6.17.1
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! electron@7.1.7 postinstall: `node install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the electron@7.1.7 postinstall script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the electron package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs electron
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls electron
> npm ERR! There is likely additional logging output above.
> npm verb exit [ 1, true ]
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/npm-debug.log
> npm ERR! code 1
> ```

something wrong with Electron. Done with it.
