### ISSUE TITLE
first demo error

### ISSUE THREAD

**Issue by policeme** [faressoft/terminalizer#93]
when I installed terminalizer, I got this error when I ran your first demo
```
cally:~ maxiong$ terminalizer record demo
/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Proxy.DI.require (/usr/local/lib/node_modules/terminalizer/di.js:105:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/app.js:29:4)
```

**Comment by policeme** [comment]
@faressoft
