### ISSUE TITLE
Failing to run terminalizer/record on node v14.0.0

### ISSUE THREAD

**Issue by mrz1836** [faressoft/terminalizer#99]
OS:
```
macOs High Sierra
Version 10.13.6
```

Version of Node:
```
$ node -v
v14.0.0
```

Installed terminalizer:
```
npm install -g terminalizer
```

Running a simple `record` command
```
$ terminalizer record gif

internal/modules/cjs/loader.js:584
            if (e.code !== 'ERR_PACKAGE_PATH_NOT_EXPORTED') throw e;
                                                            ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "index.js" defined in the package config /usr/local/lib/node_modules/terminalizer/node_modules/is-promise/package.json
    at resolveExportsTarget (internal/modules/cjs/loader.js:542:13)
    at resolveExportsTarget (internal/modules/cjs/loader.js:581:20)
    at applyExports (internal/modules/cjs/loader.js:455:14)
    at resolveExports (internal/modules/cjs/loader.js:508:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:632:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminalizer/node_modules/run-async/index.js:3:17) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
```

**Comment by mrz1836** [comment]
This resolved itself. Some dependency had an issue.... :-(
